version: '3'

services:
  # Database
  # couchserver:
  #   image: couchdb
  #   restart: always
  #   ports:
  #     - "5984:5984"
  #   environment:
  #     - COUCHDB_USER=root
  #     - COUCHDB_PASSWORD=root
  #   volumes:
  #       - ./dbdata:/opt/couchdb/data

  db:
    image: mysql:5.7
    container_name: db_container
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  # phpmyadmin
  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - "8080:80"

  # postgres:
  #   container_name: pg_container
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"

  # mongodb:
  #   image: mongo
  #   container_name: mongodb
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #   volumes:
  #     - ./mongodb:/data/db
  #   ports:
  #     - "27017:27017"
  #   restart: always

  # wordpress:
  #   image: wordpress
  #   links:
  #     - db
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_USER: root
  #     WORDPRESS_DB_PASSWORD: root
  #     WORDPRESS_DB_NAME: wordpress
  #   ports:
  #     - "81:80"
  #   volumes:
  #     - ./html:/var/www/html

  # redis:
  #   image: redis
  #   container_name: cache
  #   ports:
  #     - "6379:6379"
  #   restart: always

volumes:
  db_data:
  # postgres-data:
  # mongodb:
